### ISSUE TITLE
transport.vfs.passive parameters for ftp is not working anymore in version 6.2 and above 

### ISSUE THREAD

**Issue by dartigue** [wso2/product-ei#2345]
Creating an Inbound Endpoint for a standard FTP that is on a different network.
The inbound End point can read file and transfers them in WSO2 EI 6.1
After upgrading to 6.2,  I get an error message " 
Unable to Access to Read file or directory  

**Suggested Labels:**
vfs ftp  passive

**Suggested Assignees:**

**Affected Product Version:**
6.2 and above ( tested up to 6.3.10)
**OS, DB, other environment details and versions:**    
Windows 10 and  Linux
**Steps to reproduce:**
Create an inbound endpoint  , to connect to a FTP using vfs.
make sure the FTP require passive mode to connect, 
specify transport.vfs.passive = true as parameter  ( tried to with vfs.passive same result)
![inbound example](https://user-images.githubusercontent.com/32332175/41509278-ee93fc28-7283-11e8-9766-c97e5a609bbb.GIF)

**Comment by dartigue** [comment]
Sorry for coming back to this one, but this is a regression error, and is somewhat critical since connecting to ftp that resides in other domain ( i.e requiring passive mode), is a common scenario.   could it be possible to add such tag ( priority)

**Comment by dartigue** [comment]
Hi

I tried again the scenario with 6.3 rc2., but still the same problem ,  the same proxy service works if downgrade to 6.1
Here is the log I got today when trying with 6.3 Rc2
[2018-07-06 08:29:32,892] [EI-Core]  WARN - FtpClientFactory$FtpConnectionFactory Invalid connection timeout null. Set the connectionTimeout as 5000. (default)
[2018-07-06 08:29:32,892] [EI-Core]  WARN - FtpClientFactory$FtpConnectionFactory Invalid connection retry count null. Set the connectionRetryCount as 5. (default)
[2018-07-06 08:29:33,522] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 220 Nordic FTP
[2018-07-06 08:29:33,522] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory USER ifsint
[2018-07-06 08:29:33,826] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 331 Please specify the password.
[2018-07-06 08:29:33,826] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory PASS ***
[2018-07-06 08:29:34,150] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 230 Login successful.
[2018-07-06 08:29:34,151] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory TYPE I
[2018-07-06 08:29:34,519] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 200 Switching to Binary mode.
[2018-07-06 08:29:34,519] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory SYST
[2018-07-06 08:29:34,836] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 215 UNIX Type: L8
[2018-07-06 08:29:34,836] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory PORT 192,168,200,192,225,48
[2018-07-06 08:29:35,153] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 200 PORT command successful. Consider using PASV.
[2018-07-06 08:29:35,153] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory LIST
[2018-07-06 08:29:56,649] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 425 Failed to establish connection.
[2018-07-06 08:29:56,649] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory PWD
[2018-07-06 08:29:56,964] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 257 "/"
[2018-07-06 08:29:56,964] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory CWD OUT/VERIFY/IN
[2018-07-06 08:29:57,573] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 250 Directory successfully changed.
[2018-07-06 08:29:57,573] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory PORT 192,168,200,192,225,65
[2018-07-06 08:29:57,882] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 200 PORT command successful. Consider using PASV.
[2018-07-06 08:29:57,882] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory LIST
[2018-07-06 08:30:35,482] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 425 Failed to establish connection.
[2018-07-06 08:30:35,482] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory PORT 192,168,200,192,225,93
[2018-07-06 08:30:35,795] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 200 PORT command successful. Consider using PASV.
[2018-07-06 08:30:35,796] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory LIST
[2018-07-06 08:30:58,209] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 425 Failed to establish connection.
[2018-07-06 08:30:58,209] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory CWD /
[2018-07-06 08:30:58,623] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 250 Directory successfully changed.
[2018-07-06 08:30:58,624] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory QUIT
[2018-07-06 08:30:58,943] [EI-Core] DEBUG - FtpClientFactory$FtpConnectionFactory 221 Goodbye.

For 6.1 I get the following log on same proxy service
[2018-07-06 08:38:55,260] DEBUG -  Polling: ftp://ifsint:OLmar1117@192.9.200.97/OUT/VERIFY/IN/Message?vfs.passive=true {org.apache.synapse.transport.vfs.VFSTransportListener}
[2018-07-06 08:38:55,260] DEBUG -  Scanning directory or file : ftp://xxxxxx":***@"192.9.200.97/OUT/VERIFY/IN/Message?vfs.passive=true {org.apache.synapse.transport.vfs.VFSTransportListener}
[2018-07-06 08:39:00,137] DEBUG -  File name pattern : .*[.][cC][sS][vV]$ {org.apache.synapse.transport.vfs.VFSTransportListener}
[2018-07-06 08:39:01,377] DEBUG -  Non-Matching file : SEND_PURCHASE_ORDER472620180205_105656_CET.xml {org.apache.synapse.transport.vfs.VFSTransportListener}
[2018-07-06 08:39:01,377] DEBUG -  Non-Matching file : XSLT_7B1.xml {org.apache.synapse.transport.vfs.VFSTransportListener}
[2018-07-06 08:39:08,722]  WARN -  Unable to set file length or last modified date header. {org.wso2.carbon.inbound.endpoint.protocol.file.FilePollingConsumer} org.apache.commons.vfs2.FileSystemException: Could not determine the size of "ftp://ifsint:***@192.9.200.97/ERROR/TEST?vfs.passive=true" because it is not a file.
Note: The error is ok, since it is trying to read a subfolder…

Thank you
gilles

**Comment by Nirothipan** [comment]
Hi @dartigue,

The correct parameter name is **vfs.passive**, could you please tell us, whether you tried with this name in 6.3.0 rc-2 or the "transport.vfs.passive". If not, can you please try with the correct name and update us the status?

Thanks

**Comment by dartigue** [comment]
Hi  Nirothipan

Indeed there was some older blog stating to use transport.vfs.passive vs vfs.passive but I tried both in 6.3.0 rec-2 and both failed.
I’ might be confused, but wasn’t that issue just fixed in 6.4 m2  and the root cause was parameters in URL were not considered  ?

Thank you
Gilles dartiguenave

**Comment by 2437850** [comment]
Hi Team,

Is this working now in version EI 6.3.0

**Comment by dartigue** [comment]
Yes , it is now working

Thank you

**Comment by 2437850** [comment]
Hi dartigue,

I am still getting error like below:

{org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,399] DEBUG -  PORT xx,xx,z,qw,137,149
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,400] DEBUG -  26 : manage_menu : config_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,400] DEBUG -  501 Server cannot accept argument.
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,400] DEBUG -  PWD
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,400] DEBUG -  27 : manage_menu : mediation_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,401] DEBUG -  257 "/" is current directory.
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,401] DEBUG -  CWD InvoiceReport
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,401] DEBUG -  28 : manage_menu : libs_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,401] DEBUG -  29 : manage_menu : libs_list_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,401] DEBUG -  250 CWD command successful.
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,402] DEBUG -  PORT xx,xx,z,qw,137,19
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,402] DEBUG -  30 : manage_menu : libs_add_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,402] DEBUG -  501 Server cannot accept argument.
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,403] DEBUG -  CWD /
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,403] DEBUG -  31 : manage_menu : secure_vault_main_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,403] DEBUG -  32 : manage_menu : secure_vault_list_view {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,403] DEBUG -  33 : manage_menu : templates_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,403] DEBUG -  250 CWD command successful.
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,404] DEBUG -  Unable to access or read file or directory : ftp://ECBAdmin":***@"we.bn.qw.ko:21/InvoiceReport/Producer?vfs.passive=true. Reason: The file does not exists! {org.apache.synapse.transport.vfs.VFSTransportListener}
[2018-11-11 18:33:57,404] DEBUG -  close fs: ftp://ECBAdmin:MetraTech123@we.bn.qw.ko/?vfs.passive=true {org.apache.commons.vfs2.cache.SoftRefFilesCache}
[2018-11-11 18:33:57,404] DEBUG -  QUIT
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}
[2018-11-11 18:33:57,404] DEBUG -  34 : manage_menu : messageProcessor_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,404] DEBUG -  35 : manage_menu : messageStore_menu {org.wso2.carbon.ui.MenuAdminClient}
[2018-11-11 18:33:57,405] DEBUG -  221 Goodbye.
 {org.apache.commons.vfs2.provider.ftp.FtpClientFactory$FtpConnectionFactory}


I am still getting The file does not exists!.

Also, I have tried with both vfs.passive=true and transport.vfs.passive=true

I am currently using EI 6.3.0, so you said its working , in which version is it working? can you please specify?

**Comment by 2437850** [comment]
Thanks Dartiguenave. Its working in version 6.4.0

**Comment by sdkottegoda** [comment]
Resolved
