### ISSUE TITLE
Warning at the booting of EI server

### ISSUE THREAD

**Issue by leon001** [wso2/product-ei#251]
When start the EI server from the Developer Studio, it gets stuck at a step with following warning message repeatedly,
[2017-02-24 22:55:18,474] [EI-Core]  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:
[2017-02-24 22:55:18,477] [EI-Core]  WARN - CarbonServerManager Waiting for required Module: rampart-core-1.6.1-wso2v24

Is my fault or a bug?

**Comment by leon001** [comment]
finally, the booting process fails due to the error timeout with the message,
Server WSO2 Enterprise Integrator 6.0.0 at localhost was unable to start within 600 seconds. If the server requires more time, try increasing the timeout in the server editor.

**Comment by nandika** [comment]
This issue has been fixed in developer studio and available as an update. Go to Developer Studio => Check for updates option and install the following updates.

1 ) ESB Diagram Editor
2 ) ESB Tooling Feature
3 ) WSO2 Data Mapper Editor Feature
4 ) WSO2 ESB tool dependencies
5 ) WSO2 Enterprise Integrator Feature

**Comment by leon001** [comment]
Dear Nandika,
   Thanks for your response.
   I've tried the 'Check for update' in the Developer Studio (The standard package from WSO2, i.e. Mars based). But it replies no update as you list, instead, only Graphiti is available (and not compatible, see enclosed screenshot).
   What should I do next.
Thanks a lot.
Regards,
Leon


--
Prof. Liang ZHANG (Leon) Ph.D School of Computer Science Fudan University, Shanghai, 200433 China +86-21-65642219 Tel. +86-21-51355558 Fax +86-18930692817 Mobile. +86-13916354953 Mobile. lzhang@fudan.edu.cn email
-----Original Messages-----

**Comment by leon001** [comment]
Hi, Nandika,
   Today I suddenly recognize that I should use WSO2 update instead Eclipse update.
   Once I updated, the EI server works well. 
Thanks a lot.
Regards,
Leon



--
Prof. Liang ZHANG (Leon) Ph.D School of Computer Science Fudan University, Shanghai, 200433 China +86-21-65642219 Tel. +86-21-51355558 Fax +86-18930692817 Mobile. +86-13916354953 Mobile. lzhang@fudan.edu.cn email
-----Original Messages-----

**Comment by diegobrock** [comment]
Hi Nandika and Leon001,

At the moment there is no update available for me and the problem to start the server via developer studio (mars ei) persists.

Leon001, did it take any action other than updating Developer studio (Developer Studio -> Check Updates)?

Sorry for bad English (By Google Translator) =P

Regards,

Diego Brock

**Comment by leon001** [comment]
Dear Diego, and Nandika,
   I've ever thought that the issue was repaired once I updated from Developer Studio Menu item -> Check for Update successfully as Nandika suggested. Unfortunately, the issue still remains. I test in both Mac OS and Ubuntu 16.04 with the official Developer Studio issued from WSO2.
  @Nandika, would you try to test again? Thanks.
Regards,
Leon 


--
Prof. Liang ZHANG (Leon) Ph.D School of Computer Science Fudan University, Shanghai, 200433 China +86-21-65642219 Tel. +86-21-51355558 Fax +86-18930692817 Mobile. +86-13916354953 Mobile. lzhang@fudan.edu.cn email
-----Original Messages-----

**Comment by diegobrock** [comment]
Hello,

In my case no update is found.

I'm testing with the distributed version along with wso2ei (based on mars) for linux x86-64

My environment is as follows:
Fedora 23 x86-64
Java: 1.8.0_73
WSO2 Enterprise Integrator 6.0.0
Developer Studio Kernel 4.1.0.20160715065


Regards,

Diego Brock

**Comment by leon001** [comment]
Dear Diego,
  Please find the update from the "Developer Studio" menu item, instead of regular update from eclipse ( in the help menu item).
  However, the issue remains the same on my laptop (Mac OS and Ubuntu 16.04), even I upgraded.
Regards,
Leon


--
Prof. Liang ZHANG (Leon) Ph.D School of Computer Science Fudan University, Shanghai, 200433 China +86-21-65642219 Tel. +86-21-51355558 Fax +86-18930692817 Mobile. +86-13916354953 Mobile. lzhang@fudan.edu.cn email
-----Original Messages-----

**Comment by leon001** [comment]
The message in the console view is:
------------

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

[2017-03-13 21:05:29,134] [EI-Core]  INFO - CarbonCoreActivator Starting WSO2 Carbon...

[2017-03-13 21:05:29,138] [EI-Core]  INFO - CarbonCoreActivator Operating System : Mac OS X 10.12.3, x86_64

[2017-03-13 21:05:29,138] [EI-Core]  INFO - CarbonCoreActivator Java Home        : /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/jre

[2017-03-13 21:05:29,138] [EI-Core]  INFO - CarbonCoreActivator Java Version     : 1.8.0_112

[2017-03-13 21:05:29,139] [EI-Core]  INFO - CarbonCoreActivator Java VM          : Java HotSpot(TM) 64-Bit Server VM 25.112-b16,Oracle Corporation

[2017-03-13 21:05:29,139] [EI-Core]  INFO - CarbonCoreActivator Carbon Home      : /Users/leon/Applications/wso2ei-6.0.0

[2017-03-13 21:05:29,139] [EI-Core]  INFO - CarbonCoreActivator Java Temp Dir    : /Users/leon/Applications/wso2ei-6.0.0/tmp

[2017-03-13 21:05:29,139] [EI-Core]  INFO - CarbonCoreActivator User             : leon, en-US, Asia/Shanghai

[2017-03-13 21:05:29,270] [EI-Core]  WARN - ValidationResultPrinter Swap Memory size (MB): 1024 of the system is below the recommended minimum size :2048

[2017-03-13 21:05:29,271] [EI-Core]  WARN - ValidationResultPrinter Carbon is configured to use the default keystore (wso2carbon.jks). To maximize security when deploying to a production environment, configure a new keystore with a unique password in the production server profile.

[2017-03-13 21:05:29,286] [EI-Core]  INFO - GoogleTokenGenDSComponent Activating GoogleTokengen DS component

[2017-03-13 21:05:29,452] [EI-Core]  INFO - KafkaEventAdapterServiceDS Successfully deployed the Kafka output event adaptor service

[2017-03-13 21:05:29,520] [EI-Core]  INFO - ManagementModeConfigurationLoader CEP started in Single node mode

[2017-03-13 21:05:33,687] [EI-Core]  INFO - EmbeddedRegistryService Configured Registry in 70ms

[2017-03-13 21:05:33,739] [EI-Core]  INFO - RegistryCoreServiceComponent Registry Mode    : READ-WRITE

[2017-03-13 21:05:35,946] [EI-Core]  INFO - SolrClient Default Embedded Solr Server Initialized

[2017-03-13 21:05:36,206] [EI-Core]  INFO - UserStoreMgtDSComponent Carbon UserStoreMgtDSComponent activated successfully.

[2017-03-13 21:05:54,524] [EI-Core]  INFO - TaglibUriRule TLD skipped. URI: http://tiles.apache.org/tags-tiles is already defined

[2017-03-13 21:06:56,086] [EI-Core]  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:

[2017-03-13 21:06:56,089] [EI-Core]  WARN - CarbonServerManager Waiting for required Module: rampart-core-1.6.1-wso2v24

[2017-03-13 21:07:56,084] [EI-Core]  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:

[2017-03-13 21:07:56,084] [EI-Core]  WARN - CarbonServerManager Waiting for required Module: rampart-core-1.6.1-wso2v24

[2017-03-13 21:08:56,082] [EI-Core]  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:

[2017-03-13 21:08:56,083] [EI-Core]  WARN - CarbonServerManager Waiting for required Module: rampart-core-1.6.1-wso2v24

[2017-03-13 21:09:56,082] [EI-Core]  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:

[2017-03-13 21:09:56,082] [EI-Core]  WARN - CarbonServerManager Waiting for required Module: rampart-core-1.6.1-wso2v24

[2017-03-13 21:10:56,082] [EI-Core]  WARN - CarbonServerManager Carbon initialization is delayed due to the following unsatisfied items:

[2017-03-13 21:10:56,082] [EI-Core]  WARN - CarbonServerManager Waiting for required Module: rampart-core-1.6.1-wso2v24

-------------------------

**Comment by diegobrock** [comment]
Hello Leon001,

I found a possible solution to our problem with initializing ei within eclipse.

In summary, upgrade your java version to 1.8.0.121 and clean the <EI-HOME> / wso2 / lib folder as explained in the comments on the link below.

Http://stackoverflow.com/questions/42591512/wso2ei-6-0-0-can-not-start-in-eclipse

I took the test here and it worked, I hope it helps you.

Regards,

Diego Brock

**Comment by leon001** [comment]
Dear Diego,
   Thanks for your message. I'd try it out.
Regards,
Leon

**Comment by leon001** [comment]
Hi, Diego,
   Yes. It works. Thanks.
   BTW, I cannot develop axis 2 web services in a contract-first way. The development is error free (from the wso2 tutorials), but when they are deployed in the WSO2 application server) and test from there, the in message only display </body>. Could you or someone can give some advices?
Regards,
Leon

**Comment by diegobrock** [comment]
Hello Leon,

Although I configured the server for eclipse, I still could not deploy the applications to the server through IDE.

In my test applications (.car) after doing manual deploy through the console everything works normally.

If I find out anything, I'll let you know.

Best regards

**Comment by leon001** [comment]
Thanks for your message.
Yes, the IDE fails every time.
Leon

**Comment by nandika** [comment]
This issue is addressed in new ei tooling release.

https://github.com/wso2/devstudio-tooling-ei/releases/tag/Released-1.1.0-release-2017-03-27-162435

**Comment by leon001** [comment]
Hi,
   Thanks for your new release. I'm trying it now.
   BTW, could you tell me why the DevStudio-ei release does not provide SOAP-based service widgets any more?
Regards,
Leon

-----Original Messages-----
